import random
from datetime import date

customers_data = [
    {"customer_id": 1, "name": "Alice Johnson", "email": "alice.johnson@example.com", "registration_date": date(2023, 1, 15)},
    {"customer_id": 2, "name": "Bob Smith", "email": "bob.smith@example.com", "registration_date": date(2023, 2, 20)},
    {"customer_id": 3, "name": "Charlie Brown", "email": "charlie.brown@example.com", "registration_date": date(2023, 3, 5)},
    {"customer_id": 4, "name": "Diana Prince", "email": "diana.prince@example.com", "registration_date": date(2023, 4, 10)},
    {"customer_id": 5, "name": "Ethan Hunt", "email": "ethan.hunt@example.com", "registration_date": date(2023, 5, 25)},
    {"customer_id": 6, "name": "Fiona Gallagher", "email": "fiona.gallagher@example.com", "registration_date": date(2023, 6, 30)},
    {"customer_id": 7, "name": "George Michaels", "email": "george.michaels@example.com", "registration_date": date(2023, 7, 15)},
    {"customer_id": 8, "name": "Hannah Baker", "email": "hannah.baker@example.com", "registration_date": date(2023, 8, 10)},
    {"customer_id": 9, "name": "Ian Curtis", "email": "ian.curtis@example.com", "registration_date": date(2023, 9, 5)},
    {"customer_id": 10, "name": "Julia Roberts", "email": "julia.roberts@example.com", "registration_date": date(2023, 10, 20)},
]

products_data = [
    {"product_id": 1, "name": "Laptop", "category": "Electronics", "price": 999.99},
    {"product_id": 2, "name": "Smartphone", "category": "Electronics", "price": 699.99},
    {"product_id": 3, "name": "Headphones", "category": "Electronics", "price": 150.49},
    {"product_id": 4, "name": "Smartwatch", "category": "Electronics", "price": 199.99},
    {"product_id": 5, "name": "TV", "category": "Electronics", "price": 549.99},
    {"product_id": 6, "name": "Coffee Maker", "category": "Appliances", "price": 89.99},
    {"product_id": 7, "name": "Blender", "category": "Appliances", "price": 49.99},
    {"product_id": 8, "name": "Microwave", "category": "Appliances", "price": 129.99},
    {"product_id": 9, "name": "Fridge", "category": "Appliances", "price": 799.99},
    {"product_id": 10, "name": "Sofa", "category": "Furniture", "price": 399.99},
    {"product_id": 11, "name": "Table", "category": "Furniture", "price": 249.99},
    {"product_id": 12, "name": "Chair", "category": "Furniture", "price": 89.99},
    {"product_id": 13, "name": "Bookshelf", "category": "Furniture", "price": 149.99},
    {"product_id": 14, "name": "Lamp", "category": "Furniture", "price": 29.99},
    {"product_id": 15, "name": "Desk", "category": "Furniture", "price": 199.99}
]

statuses = ['fullfilled', 'cancelled', 'processed']
orders_data = [
    {"order_id": 1, "customer_id": random.randint(1, 10), "order_date": date(2023, 1, 10), "status": random.choice(statuses)},
    {"order_id": 2, "customer_id": random.randint(1, 10), "order_date": date(2023, 1, 15), "status": random.choice(statuses)},
    {"order_id": 3, "customer_id": random.randint(1, 10), "order_date": date(2023, 2, 20), "status": random.choice(statuses)},
    {"order_id": 4, "customer_id": random.randint(1, 10), "order_date": date(2023, 3, 5), "status": random.choice(statuses)},
    {"order_id": 5, "customer_id": random.randint(1, 10), "order_date": date(2023, 4, 10), "status": random.choice(statuses)},
    {"order_id": 6, "customer_id": random.randint(1, 10), "order_date": date(2023, 5, 25), "status": random.choice(statuses)},
    {"order_id": 7, "customer_id": random.randint(1, 10), "order_date": date(2023, 6, 30), "status": random.choice(statuses)},
    {"order_id": 8, "customer_id": random.randint(1, 10), "order_date": date(2023, 7, 15), "status": random.choice(statuses)},
    {"order_id": 9, "customer_id": random.randint(1, 10), "order_date": date(2023, 8, 10), "status": random.choice(statuses)},
    {"order_id": 10, "customer_id": random.randint(1, 10), "order_date": date(2023, 9, 5), "status": random.choice(statuses)},
    {"order_id": 11, "customer_id": random.randint(1, 10), "order_date": date(2023, 10, 20), "status": random.choice(statuses)},
    {"order_id": 12, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 10), "status": random.choice(statuses)},
    {"order_id": 13, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 11), "status": random.choice(statuses)},
    {"order_id": 14, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 12), "status": random.choice(statuses)},
    {"order_id": 15, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 14), "status": random.choice(statuses)},
    {"order_id": 16, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 14), "status": random.choice(statuses)},
    {"order_id": 17, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 14), "status": random.choice(statuses)},
    {"order_id": 18, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 17), "status": random.choice(statuses)},
    {"order_id": 19, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 17), "status": random.choice(statuses)},
    {"order_id": 20, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 18), "status": random.choice(statuses)},
    {"order_id": 21, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 19), "status": random.choice(statuses)},
    {"order_id": 22, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 20), "status": random.choice(statuses)},
    {"order_id": 23, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 22), "status": random.choice(statuses)},
    {"order_id": 24, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 22), "status": random.choice(statuses)},
    {"order_id": 25, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 22), "status": random.choice(statuses)},
    {"order_id": 26, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 22), "status": random.choice(statuses)},
    {"order_id": 27, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 25), "status": random.choice(statuses)},
    {"order_id": 28, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 26), "status": random.choice(statuses)},
    {"order_id": 29, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 27), "status": random.choice(statuses)},
    {"order_id": 30, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 28), "status": random.choice(statuses)},
    {"order_id": 31, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 28), "status": random.choice(statuses)},
    {"order_id": 32, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 29), "status": random.choice(statuses)},
    {"order_id": 33, "customer_id": random.randint(1, 10), "order_date": date(2023, 11, 30), "status": random.choice(statuses)}
]

order_items_data = [
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
    {"order_id": random.randint(1, 33), "product_id": random.randint(1, 15), "quantity": random.randint(1, 5)},
]
